import { subDays } from 'date-fns';

export const sortingOptions = [
  { title: 'P - Asc', value: '0' },
  { title: 'P - Desc', value: '1' },
];

export const priorityOptions = [
  { title: 'P0', value: 0 },
  { title: 'P1', value: 1 },
  { title: 'P2', value: 2 },
];

export const PrevData = [
  {
    id: '1',
    status: 'completed',
    title: 'task 1',
    priority: 0,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'stress',
    date: subDays(new Date(), 2),
    team: 'Wicks',
  },
  {
    id: '2',
    status: 'pending',
    title: 'task 2',
    priority: 0,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'ging',
    date: new Date(),
    team: 'Geeks',
  },
  {
    id: '3',
    status: 'deffered',
    title: 'task 3',
    priority: 0,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mello',
    date: new Date(),
    team: 'Avengers',
  },
  {
    id: '4',
    status: 'deployed',
    title: 'task 4',
    priority: 0,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'nzi3a',
    date: subDays(new Date(), 2),
    team: 'Geeks',
  },
  {
    id: '5',
    status: 'progress',
    title: 'task 5',
    priority: 0,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mama',
    date: new Date(),
    team: 'Geeks',
  },
  {
    id: '6',
    status: 'completed',
    title: 'task 6',
    priority: 2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'stress',
    date: subDays(new Date(), 4),
    team: 'Geeks',
  },
  {
    id: '7',
    status: 'pending',
    title: 'task 7',
    priority: 2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'ging',
    date: subDays(new Date(), 2),
    team: 'Geeks',
  },
  {
    id: '8',
    status: 'deffered',
    title: 'task 8',
    priority: 2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mello',
    date: new Date(),
    team: 'Geeks',
  },
  {
    id: '9',
    status: 'deployed',
    title: 'task 9',
    priority: 2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'nzi3a',
    date: new Date(),
    team: 'Geeks',
  },
  {
    id: '10',
    status: 'progress',
    title: 'task 10',
    priority: 2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mama',
    date: new Date(),
    team: 'Geeks',
  },
  {
    id: '11',
    status: 'completed',
    title: 'task 11',
    priority: 1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'stress',
    date: subDays(new Date(), 10),
    team: 'Ben 10',
  },
  {
    id: '12',
    status: 'pending',
    title: 'task 12',
    priority: 1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'ging',
    date: subDays(new Date(), 8),
    team: 'Avengers',
  },
  {
    id: '13',
    status: 'deffered',
    title: 'task 13',
    priority: 1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mello',
    date: subDays(new Date(), 6),
    team: 'Power puff',
  },
  {
    id: '14',
    status: 'deployed',
    title: 'task 14',
    priority: 1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'nzi3a',
    date: subDays(new Date(), 8),
    team: 'ninja',
  },
  {
    id: '15',
    status: 'progress',
    title: 'task 15',
    priority: 1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor corrupti accusamus animi dolorum quam id repellat enim autem exercitationem voluptate.',
    assignee: 'mama',
    date: subDays(new Date(), 8),
    team: 'Boomers',
  },
];
